### ISSUE TITLE
question about font family

### ISSUE THREAD

**Issue by dagolinuxoid** [luizfnunes/JacWin10#5]
Hi there. The theme is absolutely stunning!! I wonder what kind of font you're using for title bars? It looks like it is fixed since it can't be changed via window manager > style > title font.

**Comment by luizfnunes** [comment]
Hello. The theme uses the system default "Sans" font in the title bar. I believe that in order to change the font, you should go to the file **JacWin10/xfwm4/themerc** and delete the line:

title_font= Sans 9

**Comment by dagolinuxoid** [comment]
Thank you so much. You are correct. I consider to change the title font Noto Sans ... probably. There is a screenshot of my setup. I'm happy to be able to make xfce looks decent. [![windows-theme.png](https://i.postimg.cc/g029xccF/windows-theme.png)](https://postimg.cc/Bjk7y01M)
